name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/edge
      endpoint: NHSDigital
  pipelines:
  - pipeline: build_pipeline
    source: "Elective-Waiting-List-Api-Build"
    trigger:
      branches:
        include:
          - refs/tags/v*

pool:
  name: 'AWS-ECS'

variables:
  - template: project.yml

extends:
  template: azure/common/apigee-deployment.yml@common
  parameters:
    service_name: ${{ variables.service_name }} 
    short_service_name: ${{ variables.short_service_name }} 
    service_base_path: ${{ variables.service_base_path }}
    prod_requires_approval: false
    manual_approval_env: ${{ variables.service_name }}
    apigee_deployments:
      - environment: internal-dev
        post_deploy:
          - template: ./templates/run-tests.yml
            parameters:
              full: true
      - environment: int
        depends_on:
          - internal_dev
      - environment: manual-approval
        stage_name: prod_approval
        depends_on:
          - int
      - environment: prod
        depends_on:
          - prod_approval
